### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by bencresty** [BlenderBoi/Viewfinder#1]
This add on has the same installation issue as the Frame Ranger addon taken from github has (see https://github.com/BlenderBoi/Frame_Ranger/issues/1)

![image](https://user-images.githubusercontent.com/69322733/210169219-64256b0b-12e2-4f4b-9223-57a3162db26d.png)

Using Blender 3.4.1 on Windows.

**Comment by BlenderBoi** [comment]
Hi, the Actual Fix Actually is just Renaming the folder in the zip from Viewfinder-master to Viewfinder

The Repo are not Plug And Play Yet, will need some time to go through all my addons

(The Ones that are on Blendermarket / Gumroads are already renamed properly)

**Comment by bencresty** [comment]
Thanks. Also here; after installing the renamed folder it works!
